
name: rope_long_context_evaluation_suite
channels:
  - conda-forge
  - pytorch
  - nvidia
  - huggingface
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - transformers>=4.30.0
  - datasets>=2.14.0
  - accelerate>=0.20.0
  - tokenizers>=0.13.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pip
  - pip:
    - omegaconf>=2.3.0
    - hydra-core>=1.3.0
    - wandb>=0.15.0
    - openai>=1.0.0
    - anthropic>=0.7.0
    - einops>=0.7.0
    - flash-attn>=2.0.0
    - bitsandbytes>=0.41.0
    - peft>=0.4.0
    
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - pytest-xdist>=3.3.0
    
    
    - black>=23.7.0
    
    
    - isort>=5.12.0
    
    
    - flake8>=6.0.0
    
    
    - mypy>=1.5.0
    
    - pre-commit>=3.3.0
    - rouge-score>=0.1.2
    - nltk>=3.8.1
    - bert-score>=0.3.13
    - sacrebleu>=2.3.1
    - evaluate>=0.4.0
